"""Add new field

Revision ID: 63497af49329
Revises: 999fcb76cee6
Create Date: 2021-04-12 10:51:56.266965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63497af49329'
down_revision = '999fcb76cee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('reply', sa.String(length=20), nullable=True))
    op.add_column('contact', sa.Column('reply_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'reply_status')
    op.drop_column('contact', 'reply')
    # ### end Alembic commands ###
